name: HTML Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Requried will all actions
      - name: Checks HTML5
        uses: Cyb3r-Jak3/html5validator-action
        with:
          root: ./
